#pragma once

#include <vector>
#include <memory>
#include <stdexcept>
#include <exception>
#include <functional>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <iomanip>
#include <string>
#include <SDL3/SDL.h>
#include <../libs/SDL_mixer/include/SDL3_mixer/SDL_mixer.h>
#include <SDL3/SDL_video.h>
#include <SDL3_image/SDL_image.h>
#include <SDL3_ttf/SDL_ttf.h>
#include <iostream>
#include <fstream>
#include <sstream>
#include <filesystem>
#include <core/gkc_main.h>
#include <typeindex>
#include <cxxabi.h>